import Head from "next/head";
import { FC } from "react";

interface Props {}

export const Meta: FC<Props> = () => {
  return (
    <>
      <Head>
        <title>Reborn to 寺田蘭世</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kaoninsyou.png" />
      </Head>
    </>
  );
};
